name: '@paritytech/evidences-action'
description: 'A GitHub Action aiming to help in the process of the fellows evidences referenda.'
author: 'Parity Technologies'

runs:
  using: node20
  main: dist/index.js
