name: Evidences action

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  contents: write

jobs:
  evidences-action:
    name: Handle an Evidence command
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/evidence') }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: paritytech/evidences-action@main
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
